kernel:
    resource: ../../src/Kernel.php
    type: annotation

user_controller:
    resource: ../../src/User/Presentation/Controller
    type: annotation

restaurant_controller:
    resource: ../../src/Restaurant/Presentation/Controller
    type: annotation

order_controller:
    resource: ../../src/Order/Presentation/Controller
    type: annotation